duqduqgo/urls.py
from django.urls import path

from duqduqgo.views import Qalendar, Birthdays

app_name = 'duqduqgo'
urlpatterns = [
    path('calendar/', Qalendar.as_view(), name='qalendar'),
    path('birthdays/', Birthdays.as_view(), name="birthdays"),
]

faqts/urls.py
from django.urls import path

from faqts.views import FaQtsView, GroupsView

app_name = 'faqts'
urlpatterns = [
    path('graphs/', FaQtsView.as_view(), name='faqts'),
    path('members/', GroupsView.as_view(), name='groups'),
]

members/urls.py
from django.urls import path

from members.views import MyPasswordChangeDoneView, MyPasswordChangeView, ProfileView, ProfileFormView

app_name = "members"

urlpatterns = [
    path('password_change/', MyPasswordChangeView.as_view(), name="password_change"),
    path('password_change/done/', MyPasswordChangeDoneView.as_view(), name="password_change_done"),
    path('info/', ProfileView.as_view(), name="profile"),
    path('info/change/', ProfileFormView.as_view(), name="profile_form"),
    # The member request pages are moved to WordPress
    # path('subscribe/', SubscribeView.as_view(), name="subscribe"),
    # path('subscribe/done/', SubscribeDoneView.as_view(), name="subscribe_done"),
]

oidc/urls.py
from django.urls import path

from oidc import views

app_name = 'oidc'
urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('auth/', views.AuthView.as_view(), name='auth'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('loggedout/', views.LoggedOutView.as_view(), name='loggedout'),
]

pages/urls.py
from django.urls import path

from pages.views import IndexView


# This is a test view, can be removed
def server_error_view(request):
    raise RuntimeError('Test')


app_name = 'pages'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('500/', server_error_view),
]

tutti/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('oidc/', include('oidc.urls')),
    path('ht/', include('health_check.urls')),
    path('penno/', include('pennotools.urls')),
    path('duqduqgo/', include('duqduqgo.urls')),
    path('members/', include('members.urls')),
    path('activities/', include('activities.urls')),
    path('', include('pages.urls')),
]

pages/templates/base.html
{% extends "body.html" %}
{% load static %}

{% block title %}{{ block.super }} · Quadrivium Members Site{% endblock %}

{% block body_class %}d-flex flex-column h-100{% endblock %}

{% block body %}
    <nav class="navbar navbar-expand-md navbar-dark bd-navbar fixed-top bg-primary">
        <a class="navbar-brand" href="{% url 'pages:index' %}">
            <img src="{% static "img/logo_white.svg" %}" height="40" alt="ESMG Quadrivium">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link {% block nav_home %}{% endblock %}" href="{% url "pages:index" %}">Home</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle {% block nav_faqts %}{% endblock %}"
                       href="#" data-toggle="dropdown">
                        Q facts
                    </a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item {% block nav_groups %}{% endblock %}"
                           href="{% url 'faqts:groups' %}">Members</a>
                        <a class="dropdown-item {% block nav_graphs %}{% endblock %}"
                           href="{% url "faqts:faqts" %}">Graphs</a>
                    </div>
                </li>
                {# Divider for board only pages #}
                {% if perms.pennotools or perms.duqduqgo or perms.members %}
                    {# The d-none/d-md-inline-block is there to hide the | when the navbar is collapsed. #}
                    <span class="navbar-text d-none d-md-inline-block">|</span>
                {% endif %}
                {% if perms.pennotools %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle {% block nav_penno %}{% endblock %}"
                           href="#" data-toggle="dropdown">
                            Pennotools
                        </a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item {% block nav_qrekening %}{% endblock %}"
                               href="{% url 'pennotools:qrekening' %}">Q-rekening</a>
                            <a class="dropdown-item {% block nav_contribution %}{% endblock %}"
                               href="{% url "pennotools:contribution" %}">Contributie</a>
                        </div>
                    </li>
                {% endif %}
                {% if perms.duqduqgo %}
                    <li class="nav-item">
                        <a class="nav-link {% block nav_qalendar %}{% endblock %}" href="{% url "duqduqgo:qalendar" %}">Calendar</a>
                    </li>
                {% endif %}
                {% if perms.members %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url "admin:index" %}">Members admin</a>
                    </li>
                {% endif %}
            </ul>

            <ul class="navbar-nav">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown">
                        <i class="fas fa-user fa-lg"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right">
                        <a class="dropdown-item {% block nav_profile %}{% endblock %}"
                           href="{% url 'members:profile' %}">Your info</a>
                        {# I've removed 'change password' because there's a link on the 'your info' page #}
                        <a class="dropdown-item" href="{% url 'oidc:logout' %}">Log out</a>
                    </div>
                </li>
            </ul>
        </div>
    </nav>

    <main class="flex-shrink-0">
        <div class="container my-3">
            {% block content %}{% endblock %}
        </div>
    </main>

    <footer class="footer mt-auto py-3">
        <div class="container">
            <small class="text-muted">
                <span class="float-left">Quadrivium Members Site · Made by Qomputer Qlub</span>
                <span class="float-right">
                    {% if SOURCE_COMMIT %}
                        Version <a href="https://github.com/mhvis/tutti/commit/{{ SOURCE_COMMIT }}"
                                   target="_blank">{{ SOURCE_COMMIT|slice:":7" }}</a>
                    {% else %}
                        Development version
                    {% endif %}
                    · <a href="https://status.esmgquadrivium.nl/" target="_blank">System status</a>
                </span>
            </small>
        </div>
    </footer>
{% endblock %}

pages/templates/base_public.html
{% extends "body.html" %}
{% load static %}

{% block body_class %}d-flex flex-column h-100{% endblock %}

{% block body %}
    <div class="flex-shrink-0">
        <div class="navbar navbar-dark bd-navbar bg-primary">
            <div class="navbar-brand mx-auto">
                <img src="{% static "img/logo_white.svg" %}" height="40" alt="ESMG Quadrivium">
            </div>
        </div>
        <div class="container py-3" style="max-width: 720px;">
            {% block content %}{% endblock %}
        </div>
    </div>
    <footer class="footer mt-auto py-3">
        <div class="container" style="max-width: 720px;">
            <span class="text-muted">Made by Qomputer Qlub—Quadrivium ICT Committee</span>
        </div>
    </footer>
{% endblock %}

pages/templates/body.html
{% load static i18n %}<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE|default:"en" }}" class="h-100">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>{% block title %}Tutti{% endblock %}</title>
    <link rel="shortcut icon" href="{% static "img/favicon32.png" %}">
    {# For now we can't install Font Awesome using NPM so we'll do it like this. #}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css"
          integrity="sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog=="
          crossorigin="anonymous"/>
</head>
<body class="{% block body_class %}{% endblock %}">

{% block body %}{% endblock %}

<script src="{% static 'bundle.js' %}"></script>
{% block extra_script %}{% endblock %}
</body>
</html>

pages/templates/staging_overlay.html
<div style="all: initial;
        position: fixed;
        top: 0;
        left: 0;
        right: 0;
        z-index: 10000;
        opacity: 0.8;
        pointer-events: none;
        text-align: center;
        background-color: #ffc107;
        font-size: 14px;
        font-family: sans-serif;
        line-height: 1.5;
        color: #212529;">
    Staging environment, changes are not applied on the live environment.
</div>