oidc/urls.py
from django.urls import path

from oidc import views

app_name = 'oidc'
urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('auth/', views.AuthView.as_view(), name='auth'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('loggedout/', views.LoggedOutView.as_view(), name='loggedout'),
]

pennotools/urls.py
from django.urls import path

from pennotools.views import QRekeningView, ContributionView, XmlMakerView

app_name = 'pennotools'
urlpatterns = [
    path('qrekening/', QRekeningView.as_view(), name='qrekening'),
    path('contributie/', ContributionView.as_view(), name='contribution'),
    path('xmlmaker/', XmlMakerView.as_view(), name='xmlmaker'),
]

tutti/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('oidc/', include('oidc.urls')),
    path('ht/', include('health_check.urls')),
    path('penno/', include('pennotools.urls')),
    path('duqduqgo/', include('duqduqgo.urls')),
    path('members/', include('members.urls')),
    path('activities/', include('activities.urls')),
    path('', include('pages.urls')),
]

pennotools/models.py
from django.db import models


class Permissions(models.Model):
    """Model that defines the app permissions, does not create a database."""

    class Meta:
        managed = False  # No db
        permissions = (
            ('can_access', 'Can use the treasurer tools'),  # Can do everything in this app
        )
        default_permissions = ()  # No default permissions (add/delete/view/change)

pennotools/forms.py
import datetime
from contextlib import contextmanager
from decimal import Decimal

from django import forms
from django.core.exceptions import ValidationError
from django.forms import Textarea
from django.utils.safestring import mark_safe

from members.models import QGroup
from pennotools.core.davilex import combine_reports, parse_davilex_report


def sepa_initial_description():
    return 'Contribution {}'.format(datetime.date.today().strftime('%Y'))


class ContributionForm(forms.Form):
    student = forms.DecimalField(decimal_places=2,
                                 min_value=0,
                                 help_text="Hoogte van de contributie voor studenten.")
    non_student = forms.DecimalField(decimal_places=2,
                                     min_value=0,
                                     label="Burger",
                                     help_text="Hoogte van de contributie voor burgers.")
    administration_fee = forms.DecimalField(decimal_places=2,
                                            min_value=0,
                                            initial=6,
                                            label="Administratiekosten",
                                            help_text="Wordt alleen toegepast bij personen zonder SEPA machtiging.")
    description = forms.CharField(help_text="Omschrijving voor de SEPA incasso.",
                                  max_length=35,
                                  initial=sepa_initial_description,
                                  label="Omschrijving")
    sepa_split = forms.DecimalField(min_value=Decimal('0.01'), decimal_places=2, label="SEPA split",
                                    help_text="SEPA debit rows with a value larger than this amount will be "
                                              "split over multiple rows.",
                                    initial=Decimal('130.00'))


class ContributionExemptionForm(forms.Form):
    group = forms.ModelChoiceField(queryset=QGroup.objects.all().order_by('name'))
    student = forms.DecimalField(decimal_places=2,
                                 min_value=0)
    non_student = forms.DecimalField(decimal_places=2,
                                     min_value=0,
                                     label="Burger")


class BaseContributionExemptionFormSet(forms.BaseFormSet):
    def clean(self):
        """Checks that the groups are unique."""
        if any(self.errors):
            # Don't bother validating the formset unless each form is valid on its own
            return
        groups = []
        for form in self.forms:
            group = form.cleaned_data.get("group")
            if not group:
                continue  # Form might be empty
            if group in groups:
                raise forms.ValidationError("Groups need to be distinct.")
            groups.append(group)


ContributionExemptionFormSet = forms.formset_factory(ContributionExemptionForm,
                                                     formset=BaseContributionExemptionFormSet,
                                                     extra=0)


def qrekening_initial_description():
    return 'Qrekening {}'.format(datetime.date.today().strftime('%B %Y'))


@contextmanager
def to_validation_error():
    """Context manager that reraises errors from parsing as ValidationError."""
    try:
        yield
    except (ValueError, IndexError) as e:
        raise ValidationError(mark_safe(
            f"Could not parse report. See code or <a href='mailto:sysop@esmgquadrivium.nl'>ask</a> for details."
            f" The error encountered was: '{e}'."))


class QRekeningForm(forms.Form):
    """Form which parses the Davilex report during cleaning.

    It shows a validation error when parsing fails.
    """
    debit = forms.CharField(widget=Textarea,
                            strip=False,
                            help_text="Debit report exported from Davilex using 'Rapport kopiëren'.")
    credit = forms.CharField(widget=Textarea, strip=False, help_text="Davilex credit report.")
    description = forms.CharField(help_text="Description shown on the debtor direct debit statement.",
                                  max_length=35,
                                  initial=qrekening_initial_description)
    sepa_split = forms.DecimalField(min_value=Decimal('0.01'), decimal_places=2, label="SEPA split",
                                    help_text="SEPA debit rows with a value larger than this amount will be "
                                              "split over multiple rows.",
                                    initial=Decimal('130.00'))

    def clean_debit(self):
        with to_validation_error():
            return parse_davilex_report(self.cleaned_data['debit'])

    def clean_credit(self):
        with to_validation_error():
            return parse_davilex_report(self.cleaned_data['credit'])

    def clean(self):
        # This method combines debit and credit on person ID
        cleaned_data = super().clean()
        debit = cleaned_data.get('debit')
        credit = cleaned_data.get('credit')
        # 'is not None' is maybe necessary in case the value is an empty list
        if debit is not None and credit is not None:
            with to_validation_error():
                cleaned_data['accounts'] = combine_reports(debit, credit)
        return cleaned_data

class XmlMakerForm(forms.Form):
    SEPA_csv_file = forms.CharField(widget=Textarea,
                            strip=False,
                            help_text="Open het SEPA csv file in Notepad and paste it in here")

pennotools/views.py
import csv

import xlsxwriter
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.http import HttpResponse
from django.views.generic import TemplateView, FormView

from pennotools.core.contribution import ContributionExemption, get_contributie, contributie_header, \
    contribution_sepa_amounts
from pennotools.core.qrekening import qrekening_sepa_amounts, get_qrekening, qrekening_header
from pennotools.core.rabo import rabo_sepa, parse_csv_dict, rabo_sepa_xml
from pennotools.core.util import split_amount
from pennotools.core.workbook import write_sheet
from pennotools.forms import ContributionForm, ContributionExemptionFormSet, QRekeningForm, XmlMakerForm


class TreasurerAccessMixin(PermissionRequiredMixin):
    """Use this mixin to protect views from prying eyes."""
    permission_required = 'pennotools.can_access'


class QRekeningView(TreasurerAccessMixin, FormView):
    template_name = 'pennotools/qrekening.html'

    form_class = QRekeningForm

    def form_valid(self, form):
        # Davilex parsing happens during form cleaning
        accounts = form.cleaned_data['accounts']

        if 'sepa' in self.request.POST:
            # Get the amounts for SEPA
            debits = split_amount(qrekening_sepa_amounts(accounts), split=form.cleaned_data['sepa_split'])

            # Create and write the Rabobank CSV
            table = rabo_sepa(debits, form.cleaned_data['description'])

            response = HttpResponse(
                content_type='text/csv',
                headers={'Content-Disposition': 'attachment; filename="rabo_sepa.csv"'},
            )
            writer = csv.writer(response, delimiter=";")
            writer.writerows(table)
            return response

        else:
            # Get Qrekening sheets
            creditors, debtors, debtors_self, external = get_qrekening(accounts)
            # Write Excel workbook in response
            response = HttpResponse(
                content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                headers={'Content-Disposition': 'attachment; filename="qrekening.xlsx"'},
            )
            workbook = xlsxwriter.Workbook(response)
            write_sheet(workbook, 'Crediteuren', qrekening_header, creditors)
            write_sheet(workbook, 'Debiteuren', qrekening_header, debtors)
            write_sheet(workbook, 'DebiteurenZelf', qrekening_header, debtors_self)
            write_sheet(workbook, 'Externen', qrekening_header, external)
            workbook.close()
            return response


class ContributionView(TreasurerAccessMixin, TemplateView):
    template_name = "pennotools/contribution.html"

    def get(self, request, *args, **kwargs):
        context = {
            "form": ContributionForm(),
            "exceptions_formset": ContributionExemptionFormSet(),
        }
        return self.render_to_response(context)

    def post(self, request, *args, **kwargs):
        form = ContributionForm(request.POST)
        exceptions_formset = ContributionExemptionFormSet(request.POST)
        if form.is_valid() and exceptions_formset.is_valid():
            # Collect exemptions
            exemptions = []
            for form_data in exceptions_formset.cleaned_data:
                # Loop over the data of all exception forms
                if not form_data.get("group"):
                    # There may be empty forms which should be ignored
                    continue
                exemptions.append(ContributionExemption(group=form_data["group"],
                                                        student=form_data["student"],
                                                        non_student=form_data["non_student"]))

            if 'contribution_file' in request.POST:
                # Get contribution sheets
                debtors, debtors_self = get_contributie(form.cleaned_data['student'],
                                                        form.cleaned_data['non_student'],
                                                        form.cleaned_data['administration_fee'], exemptions)

                # Write to response
                response = HttpResponse(
                    content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                    headers={'Content-Disposition': 'attachment; filename="contributielijst.xlsx"'},
                )
                workbook = xlsxwriter.Workbook(response)
                write_sheet(workbook, 'Debiteuren', contributie_header, debtors)
                write_sheet(workbook, 'DebiteurenZelf', contributie_header, debtors_self)
                workbook.close()
                return response
            else:
                amounts = contribution_sepa_amounts(form.cleaned_data['student'],
                                                    form.cleaned_data['non_student'],
                                                    exemptions)
                split = split_amount(amounts, split=form.cleaned_data['sepa_split'])
                table = rabo_sepa(split, form.cleaned_data['description'])

                # Write CSV
                response = HttpResponse(
                    content_type='text/csv',
                    headers={'Content-Disposition': 'attachment; filename="rabo_sepa.csv"'},
                )
                writer = csv.writer(response)
                writer.writerows(table)
                return response
        # One of the forms was not valid, render again
        context = {
            "form": form,
            "exceptions_formset": exceptions_formset,
        }
        return self.render_to_response(context)

class XmlMakerView(TreasurerAccessMixin, FormView):
    template_name = "pennotools/xml_maker.html"

    def get(self, request, *args, **kwargs):
        form = XmlMakerForm()
        return self.render_to_response({"form": form})
    
    def post(self, request, *args, **kwargs):
        data = parse_csv_dict(request.POST['SEPA_csv_file'])
        xmlbody = rabo_sepa_xml(data)
        return HttpResponse(xmlbody, content_type="application/xml")
        

pennotools/templates/pennotools/contribution.html
{% extends "base.html" %}
{% load bootstrap4 static %}

{% block title %}Contributie | {{ block.super }}{% endblock %}

{% block nav_penno %}active{% endblock %}
{% block nav_contribution %}active{% endblock %}

{% block content %}
    <h1>Contributie tool</h1>

    <form method="post" action="{% url "pennotools:contribution" %}">
        <p>Maakt contributie bestanden.</p>
        {% csrf_token %}
        {% bootstrap_form form layout="horizontal" %}
        <h2>Uitzonderingen</h2>
        <p>
            Aparte bedragen voor bepaalde groepen. Als er meerdere uitzonderingen voor een persoon gelden
            wordt het laagste bedrag toegepast.
        </p>

        {# Dynamic formset is based on https://stackoverflow.com/a/8097617 #}
        {{ exceptions_formset.management_form }}
        {% bootstrap_formset_errors exceptions_formset %}
        <div id="exceptionsFormSet">
            {% for form in exceptions_formset %}
                {% include "pennotools/contribution_exception_form.html" %}
            {% endfor %}
        </div>

        <p>
            <button type="button" id="exceptionsFormAdd" class="btn btn-success">
                <i class="fas fa-plus-circle"></i>
                <span class="sr-only">Add</span>
            </button>
        </p>

        <div id="exceptionsFormEmpty" style="display: none;">
            {% include "pennotools/contribution_exception_form.html" with form=exceptions_formset.empty_form %}
        </div>
        <div class="alert alert-warning">
            Check de gegenereerde bestanden, er kunnen fouten in zitten.
        </div>
        <p>
            <button type="submit" name="contribution_file" class="btn btn-primary">Contributielijst</button>
            <button type="submit" name="sepa_file" class="btn btn-primary">SEPA</button>
        </p>
    </form>
{% endblock %}

{% block extra_script %}
    <script>
        $('#exceptionsFormAdd').click(function () {
            let idx = $('#id_form-TOTAL_FORMS').val();
            $('#exceptionsFormSet').append($('#exceptionsFormEmpty').html().replace(/__prefix__/g, idx));
            $('#id_form-TOTAL_FORMS').val(parseInt(idx) + 1);
        });
    </script>
{% endblock %}

pennotools/templates/pennotools/contribution_exception_form.html
{% load bootstrap4 %}
<div class="row mb-3 mb-sm-0">
    {% bootstrap_form form show_label=False form_group_class="col-sm" field_class="mb-2" %}
</div>

pennotools/templates/pennotools/qrekening.html
{% extends "base.html" %}
{% load bootstrap4 static %}

{% block title %}Q-rekening | {{ block.super }}{% endblock %}

{% block nav_penno %}active{% endblock %}
{% block nav_qrekening %}active{% endblock %}

{% block content %}
    <h1>Q-rekening</h1>

    <form method="post" action="{% url 'pennotools:qrekening' %}">
        {% csrf_token %}
        {% bootstrap_form form layout="horizontal" %}
        <button type="submit" name="qrekening" class="btn btn-primary">Q-rekening</button>
        <button type="submit" name="sepa" class="btn btn-primary">SEPA CSV</button>
        <p>
            <small class="text-muted">
                The SEPA CSV file can be imported in Rabo Internetbankieren Professional (RIB Pro) and uses
                <a href="https://www.rabobank.nl/images/pdf_formaatbeschrijving_csv_29856100.pdf" target="_blank">this
                    format</a>.
            </small>
        </p>
    </form>
{% endblock %}

pennotools/templates/pennotools/xml_maker.html
{% extends "base.html" %}
{% load bootstrap4 static %}

{% block title %}XML maker | {{ block.super }}{% endblock %}

{% block nav_penno %}active{% endblock %}
{% block nav_contribution %}active{% endblock %}

{% block content %}
<h1>SEPA XML-maker</h1>
    <p>Deze tool converteert de door het qrekening en contributiescript gegenereerde SEPA csv bestand naar een xml-bestand. </p>
    <p>Let op! Controleer altijd de checksum</p>
    

    <form method="post" action="{% url 'pennotools:xmlmaker' %}">
        {% csrf_token %}
        {% bootstrap_form form layout="horizontal" %}
        <button type="submit" name="xml" class="btn btn-primary">Maak XML-bestand</button>
        <p>
            <small class="text-muted">
                The SEPA XML file can be imported in Rabo Internetbankieren Professional (RIB Pro) and uses
                <a href="https://statics.rabobank.com/binaries-processed/Formaatbeschrijving_Euro_IncassoV2_931143607.pdf" target="_blank">this
                    format</a>.
            </small>
        </p>
    </form>
{% endblock %}