members/urls.py
from django.urls import path

from members.views import MyPasswordChangeDoneView, MyPasswordChangeView, ProfileView, ProfileFormView

app_name = "members"

urlpatterns = [
    path('password_change/', MyPasswordChangeView.as_view(), name="password_change"),
    path('password_change/done/', MyPasswordChangeDoneView.as_view(), name="password_change_done"),
    path('info/', ProfileView.as_view(), name="profile"),
    path('info/change/', ProfileFormView.as_view(), name="profile_form"),
    # The member request pages are moved to WordPress
    # path('subscribe/', SubscribeView.as_view(), name="subscribe"),
    # path('subscribe/done/', SubscribeDoneView.as_view(), name="subscribe_done"),
]

oidc/urls.py
from django.urls import path

from oidc import views

app_name = 'oidc'
urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('auth/', views.AuthView.as_view(), name='auth'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('loggedout/', views.LoggedOutView.as_view(), name='loggedout'),
]

tutti/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('oidc/', include('oidc.urls')),
    path('ht/', include('health_check.urls')),
    path('penno/', include('pennotools.urls')),
    path('duqduqgo/', include('duqduqgo.urls')),
    path('members/', include('members.urls')),
    path('activities/', include('activities.urls')),
    path('', include('pages.urls')),
]

members/models.py
import uuid
from datetime import date

from django.conf import settings
from django.contrib.auth.models import AbstractUser, Group, UserManager
from django.core import validators
from django.db import models
from django.db.models import QuerySet
from django.utils import timezone
from django.utils.deconstruct import deconstructible
from django.utils.translation import gettext_lazy as _
from django_countries.fields import CountryField
from ldap3 import HASHED_SALTED_SHA512
from ldap3.utils.hashed import hashed
from localflavor.generic.models import IBANField
from phonenumber_field.modelfields import PhoneNumberField


@deconstructible
class UsernameValidator(validators.RegexValidator):
    regex = r"^[a-z0-9]+\Z"
    message = "Enter a valid username. This value may contain only lowercase letters and numbers."


class User(AbstractUser):
    """A user for authentication and groups, optionally linked to a Person."""

    ldap_password = models.CharField(max_length=256, default="")
    """Stores the password hashed in a format that LDAP understands.

    A bit invasive, but an easy solution.
    """

    # We override the username field to set a validator for only lowercase letters and numbers.
    username = models.CharField(
        max_length=150,
        unique=True,
        help_text="Required. 150 characters or fewer. Lowercase letters and numbers only.",
        validators=[UsernameValidator()],
        error_messages={"unique": _("A user with that username already exists."), },
    )
    # First and last name are required.
    first_name = models.CharField(_("first name"), max_length=150)
    last_name = models.CharField(_("last name"), max_length=150)
    email = models.EmailField(_("email address"))

    def __str__(self):
        # Default implementation returns username
        return self.get_full_name()

    def set_password(self, raw_password):
        # Hook into the password system for creating an additional hash for use
        # with LDAP.
        super().set_password(raw_password)
        self.ldap_password = hashed(HASHED_SALTED_SHA512, raw_password)


class Instrument(models.Model):
    class Meta:
        ordering = ['name']

    name = models.CharField(max_length=150, unique=True)

    def __str__(self):
        return self.name


class QGroupManager(models.Manager):
    def get_members_group(self):
        """Returns the current members group.

        If you just need the ID for filtering, use settings.MEMBERS_GROUP.
        """
        return self.get(id=settings.MEMBERS_GROUP)


class QGroup(Group):
    """Extension of the Group model for Quadrivium fields."""
    description = models.TextField(blank=True)
    email = models.EmailField(blank=True, verbose_name='e-mail')
    end_on_unsubscribe = models.BooleanField(default=True,
                                             help_text=("If set, when a person is unsubscribed they are removed "
                                                        "from this group."))
    owner = models.ForeignKey('Person',
                              on_delete=models.PROTECT,
                              null=True,
                              blank=True,
                              help_text="E.g. the commissioner. Currently not used for anything.")
    show_in_overview = models.BooleanField(default=True,
                                           help_text=("Whether the group is visible in the groups overview, "
                                                      "with group members."))
    category = models.CharField(max_length=30,
                                blank=True,
                                choices=[('committee', 'Committee'),
                                         ('ensemble', 'Ensemble'),
                                         ('subassociation', 'Sub-association')],
                                help_text="Leave empty when there's no applicable option.",
                                db_index=True)

    objects = QGroupManager()

    class Meta:
        verbose_name = 'group'
        verbose_name_plural = 'groups'


class ExternalCard(models.Model):
    card_number = models.IntegerField(null=True,
                                      blank=True,
                                      help_text="7-digit (usually) card identifier number.")
    reference_number = models.IntegerField(null=True,
                                           blank=True,
                                           help_text='Short reference number written on the card.')
    description = models.CharField(max_length=150,
                                   help_text='Additional indication that is written on the card.',
                                   blank=True)

    # decommissioned = models.BooleanField for when a card is no longer used by Q?

    def __str__(self):
        return '–'.join([str(x) for x in (self.card_number, self.reference_number, self.description) if x])


class Key(models.Model):
    number = models.IntegerField(primary_key=True)
    room_name = models.CharField(max_length=150, blank=True)

    class Meta:
        ordering = ('number',)

    def __str__(self):
        if self.room_name:
            return "{} ({})".format(self.number, self.room_name)
        else:
            return str(self.number)


class PersonQuerySet(QuerySet):
    def filter_members(self):
        """Filters people that are currently a member."""
        if settings.MEMBERS_GROUP == -1:
            # Members group ID not set, do nothing
            return self
        return self.filter(groups=settings.MEMBERS_GROUP)


class PersonManager(UserManager.from_queryset(PersonQuerySet)):
    pass


class Person(User):
    """Extends a user with Quadrivium related fields.

    We extend User (instead of a separate model) so that we can use the
    built-in groups field for group membership and make use of the permissions
    system that comes with it. The user account does not need to have a
    password set or be active.
    """

    class Meta:
        verbose_name = 'person'
        verbose_name_plural = 'people'
        permissions = [
            ('change_treasurer_fields', 'Can change treasurer related fields'),
        ]

    objects = PersonManager()

    initials = models.CharField(max_length=30, blank=True)

    # Address
    street = models.CharField(max_length=150, blank=True)
    postal_code = models.CharField(max_length=30, blank=True)
    city = models.CharField(max_length=150, blank=True)
    country = CountryField(blank=True, default='NL')

    phone_number = PhoneNumberField(blank=True)

    PREFERRED_LANGUAGES = (
        ('en-us', 'English'),
        ('nl-nl', 'Dutch'),
    )
    preferred_language = models.CharField(max_length=30,
                                          blank=True,
                                          choices=PREFERRED_LANGUAGES)
    tue_card_number = models.IntegerField(null=True,
                                          blank=True,
                                          verbose_name='TU/e card number')
    date_of_birth = models.DateField(null=True, blank=True)
    gender = models.CharField(max_length=30,
                              blank=True,
                              choices=(('male', 'Male'), ('female', 'Female')))

    photo_video_consent_internal = models.BooleanField(
        null=True,
        blank=True,
        verbose_name="photos/videos consent internal",
        help_text="Whether the person has given consent to share photos and videos of them internally with other members."
    )
    photo_video_consent_external_group = models.BooleanField(
        null=True,
        blank=True,
        verbose_name='photos/videos consent external group',
        help_text="Whether the person has given consent to share group photos and videos of them externally (on website, social media). With group is meant large groups, such as pictures of a full orchestra or choir during a concert."
    )
    photo_video_consent_external = models.BooleanField(
        null=True,
        blank=True,
        verbose_name='photos/videos consent external non-group',
        help_text="Whether the person has given consent to share other photos and videos of them externally (on website, social media)."
    )
    

    is_student = models.BooleanField(null=True, blank=True)

    sepa_direct_debit = models.BooleanField(null=True,
                                            blank=True,
                                            verbose_name='SEPA direct debit')

    instruments = models.ManyToManyField(Instrument, blank=True)

    bhv_certificate = models.DateField(null=True,
                                       blank=True,
                                       verbose_name='BHV certificate date')

    field_of_study = models.CharField(max_length=150,
                                      blank=True)

    iban = IBANField(blank=True, verbose_name='IBAN')
    person_id = models.CharField(max_length=30, blank=True, verbose_name='person ID', help_text='Davilex code.')
    sepa_sign_date = models.DateField(blank=True, null=True, verbose_name='SEPA agreement date')

    key_access = models.ManyToManyField(Key, blank=True)
    keywatcher_id = models.CharField(max_length=4, blank=True, verbose_name='KeyWatcher ID')
    keywatcher_pin = models.CharField(max_length=4, blank=True, verbose_name='KeyWatcher PIN')

    notes = models.TextField(blank=True)

    # The Azure immutable ID is used to match Azure accounts with those stored in LDAP
    azure_immutable_id = models.CharField(max_length=150, editable=False, default=uuid.uuid4, unique=True)

    def clean(self):
        # Person ID should always be uppercase
        self.person_id = self.person_id.upper()

    def current_external_card_loans(self):
        """Get current external card loans."""
        return self.externalcardloan_set.filter(end=None)

    def is_member(self):
        """Returns whether this person is currently a member."""

members/forms.py
from django import forms
from django.contrib.auth.forms import PasswordChangeForm
from ldap3.core.exceptions import LDAPInvalidCredentialsResult

from members.models import Person, MembershipRequest
from sync.ldap import get_connection


class ProfileForm(forms.ModelForm):
    """Allows the user to change some of his profile data."""

    class Meta:
        model = Person
        fields = ['email', 'phone_number', 'street', 'postal_code', 'city', 'country', 'preferred_language']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].help_text = ("If you change your email address, "
                                          "members mail will be sent to the new address.")
        # Set fields as required
        for f in ('email', 'phone_number', 'street', 'postal_code', 'city', 'country', 'preferred_language'):
            self.fields[f].required = True


def try_ldap_bind(user, password):
    """Tries to bind (login) on LDAP with given credentials."""
    conn = get_connection()
    conn.user = user
    conn.password = password
    try:
        conn.bind()
    except LDAPInvalidCredentialsResult:
        return False
    finally:
        conn.unbind()
    return True


class MyPasswordChangeForm(PasswordChangeForm):
    """Password change form that verifies old passwords on LDAP."""

    def clean_old_password(self):
        # Passwords that are only set in LDAP have value 'invalid' in Django
        if self.user.password == "invalid":
            # Try LDAP bind
            old_password = self.cleaned_data["old_password"]
            ldap_user = "uid={},ou=people,dc=esmgquadrivium,dc=nl".format(self.user.username)
            if not try_ldap_bind(ldap_user, old_password):
                raise forms.ValidationError(
                    self.error_messages['password_incorrect'],
                    code='password_incorrect',
                )
            # Bind succeeded
            return old_password
        return super().clean_old_password()


class SubscribeForm(forms.ModelForm):
    # date_of_birth = forms.DateField(input_formats=('%d-%m-%Y',), help_text="dd-mm-yyyy")

    class Meta:
        model = MembershipRequest
        fields = ['first_name', 'last_name', 'initials', 'email', 'phone_number', 'street', 'postal_code', 'city',
                  'country', 'gender', 'date_of_birth', 'preferred_language', 'field_of_study', 'is_student', 'iban',
                  'tue_card_number', 'remarks', 'instruments']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['date_of_birth'].input_formats = ('%d-%m-%Y',)

members/views.py
from datetime import date

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import PasswordChangeDoneView, PasswordChangeView
from django.urls import reverse_lazy
from django.utils.safestring import mark_safe
from django.views.generic import FormView, TemplateView

from members.forms import MyPasswordChangeForm, ProfileForm, SubscribeForm


class ProfileView(LoginRequiredMixin, TemplateView):
    """Displays info on the logged in member."""
    template_name = "members/profile.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        country = self.request.user.person.country
        memberships = self.request.user.groupmembership_set.order_by("-start")
        context.update({
            "country": mark_safe('<img src="{}" alt="{}"> {}'.format(country.flag, country.code, country.name)),
            "current_memberships": memberships.filter(end=None),
            "past_memberships": memberships.filter(end__isnull=False),
            "memberships_start": date(2020, 3, 30),
        })
        return context


class ProfileFormView(LoginRequiredMixin, FormView):
    """Page for editing own contact info."""
    template_name = "members/profile_form.html"
    form_class = ProfileForm
    success_url = reverse_lazy("members:profile")

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["instance"] = self.request.user.person
        return kwargs

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class MyPasswordChangeView(PasswordChangeView):
    template_name = "members/password_change_form.html"
    success_url = reverse_lazy("members:password_change_done")
    form_class = MyPasswordChangeForm


class MyPasswordChangeDoneView(PasswordChangeDoneView):
    template_name = "members/password_change_done.html"


class SubscribeView(FormView):
    # TODO: this view is no longer used and can be removed.
    template_name = "members/subscribe_form.html"
    form_class = SubscribeForm
    success_url = reverse_lazy('members:subscribe_done')

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class SubscribeDoneView(TemplateView):
    # TODO: this view is no longer used and can be removed.
    template_name = "members/subscribe_form_done.html"

members/templates/members/password_change_done.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block nav_password_change %}active{% endblock %}

{% block content %}
    <h1>Password change successful</h1>
    <p>Your password was changed. It can take up to 1 minute for the change to go into effect.</p>
{% endblock %}

members/templates/members/password_change_form.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block nav_password_change %}active{% endblock %}

{% block content %}
    <h1>Change password</h1>
    <p>
        Please enter your old password, for security’s sake, and then enter your new password twice so we can verify you
        typed it in correctly.
    </p>
    <form action="{% url "members:password_change" %}" method="post">
        {% csrf_token %}
        {% bootstrap_form form layout="horizontal" %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">Change my password</button>
        {% endbuttons %}
    </form>
{% endblock %}

members/templates/members/profile.html
{% extends "base.html" %}
{% load bootstrap4 static tutti_extras %}

{% block nav_profile %}active{% endblock %}

{% block content %}
    <h1>Your info</h1>

    <p>
        This is the personal and membership information that we have stored about you.
        If you would like to change your information,
        contact the secretary of Quadrivium. For data removal requests and unsubscribe requests
        you can also contact <a href="mailto:secretaris@esmgquadrivium.nl">the secretary of Quadrivium</a>.
    </p>

    <div class="row mb-2">
        <div class="col-sm-3 col-lg-2"><strong>Username</strong></div>
        <div class="col-sm-9 col-lg-10">{{ user.username }} (<a href="{% url "members:password_change" %}">change
            password</a>)
        </div>
    </div>
    {% include "members/profile_row.html" with label="Full name" value=user.get_full_name %}
    {% include "members/profile_row.html" with label="Initials" value=user.person.initials %}
    {% include "members/profile_row.html" with label="Gender" value=user.person.gender|capfirst %}
    {% include "members/profile_row.html" with label="Date of birth" value=user.person.date_of_birth %}

    <h2 class="mt-3">Contact info</h2>
    {% include "members/profile_row.html" with label="Email address" value=user.email %}
    {% include "members/profile_row.html" with label="Phone number" value=user.person.phone_number %}
    {% include "members/profile_row.html" with label="Street" value=user.person.street %}
    {% include "members/profile_row.html" with label="Postal code" value=user.person.postal_code %}
    {% include "members/profile_row.html" with label="City" value=user.person.city %}
    {% include "members/profile_row.html" with label="Country" value=country %}
    <div class="row mb-2">
        <div class="col"><a href="{% url "members:profile_form" %}">Change contact info</a></div>
    </div>

    <h2 class="mt-3">Groups</h2>

    <table class="table table-sm">
        <thead>
        <tr>
            <th scope="col">Group</th>
            <th scope="col">Since</th>
        </tr>
        </thead>
        <tbody>
        {% for membership in current_memberships %}
            <tr>
                <td>
                    {{ membership.group.name }}
                    {% if membership.group.qgroup.description %}
                        <span class="fas fa-info-circle"
                              data-toggle="tooltip"
                              data-html="true"
                              title="{{ membership.group.qgroup.description|linebreaksbr }}"></span>
                    {% endif %}
                </td>
                <td>
                    {% if membership.start.date != memberships_start %}
                        {{ membership.start.date }}
                    {% else %}
                        <i class="far fa-sm fa-question-circle"></i>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <h4>Past groups</h4>
    <div class="alert alert-info">
        Past groups might be incomplete up until March 30, 2020.
    </div>
    <table class="table table-sm">
        <thead>
        <tr>
            <th scope="col">Group</th>
            <th scope="col">Start date</th>
            <th scope="col">End date</th>
        </tr>
        </thead>
        <tbody>
        {% for membership in past_memberships %}
            <tr>
                <td>
                    {{ membership.group.name }}
                    {% if membership.group.qgroup.description %}
                        <span class="fas fa-info-circle"
                              data-toggle="tooltip"
                              data-html="true"
                              title="{{ membership.group.qgroup.description|linebreaksbr }}"></span>
                    {% endif %}
                </td>
                <td>
                    {% if membership.start.date != memberships_start %}
                        {{ membership.start.date }}
                    {% else %}
                        <i class="far fa-sm fa-question-circle"></i>
                    {% endif %}
                </td>
                <td>{{ membership.end.date }}</td>
            </tr>

        {% endfor %}
        </tbody>
    </table>


    <h2 class="mt-3">Membership info</h2>
    {% include "members/profile_row.html" with label="Instruments" value=user.person.instruments.all|join:", "|capfirst %}
    {% include "members/profile_row.html" with label="Preferred language" value=user.person.get_preferred_language_display %}
    {% include "members/profile_row.html" with label="Is student" value=user.person.is_student|yesno|capfirst %}
    {% include "members/profile_row.html" with label="Field of study" value=user.person.field_of_study %}
    {% include "members/profile_row.html" with label="IBAN" value=user.person.iban|iban %}
    {% include "members/profile_row.html" with label="SEPA direct debit" value=user.person.sepa_direct_debit|yesno|capfirst %}
    {% include "members/profile_row.html" with label="BHV certificate" value=user.person.bhv_certificate %}
    <h2 class="mt-3">KeyWatcher</h2>
    <p>With these codes you can retrieve keys for rehearsal rooms. If you need help with the KeyWatcher system, contact
        a board member.</p>
    {% include "members/profile_row.html" with label="KeyWatcher ID" value=user.person.keywatcher_id %}
    {% include "members/profile_row.html" with label="KeyWatcher PIN" value=user.person.keywatcher_pin %}
    {% include "members/profile_row.html" with label="Keys that you can access" value=user.person.key_access.all|join:", " %}

    <h2 class="mt-3">Card access</h2>
    <p>Card access for Luna during off-hours.</p>
    {% include "members/profile_row.html" with label="TU/e card number" value=user.person.tue_card_number %}
    {% with loans=user.person.externalcardloan_set.all %}
        {% if loans %}
            <table class="table table-sm">
                <thead>
                <tr>
                    <th scope="col">External card</th>
                    <th scope="col">From</th>
                    <th scope="col">To</th>
                    <th scope="col">Deposit made</th>
                </tr>
                </thead>
                <tbody>
                {% for loan in loans %}
                    <tr>
                        <td>{{ loan.external_card }}</td>
                        <td>{{ loan.start }}</td>
                        <td>{% if loan.end %}{{ loan.end }}{% else %}-{% endif %}</td>
                        <td>{{ loan.get_deposit_made_display }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p>You are not in possession of an external card.</p>
        {% endif %}
    {% endwith %}
{% endblock %}

{% block extra_script %}
    <script>
        // Enable tooltips on this page
        // Could also put this in index.js
        $(function () {
            $('[data-toggle="tooltip"]').tooltip()
        })
    </script>
{% endblock %}

members/templates/members/profile_form.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block nav_profile %}active{% endblock %}

{% block content %}
    <h1>Your info</h1>
    <p><a href="{% url "members:profile" %}">← Back to overview</a></p>
    <p>You can change your contact info here. If you want to change other details, contact the secretary.</p>
    <form action="{% url "members:profile_form" %}" method="post">
        {% csrf_token %}
        {% bootstrap_form form layout="horizontal" %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">Change</button>
        {% endbuttons %}
    </form>
{% endblock %}

members/templates/members/profile_row.html
<div class="row mb-2">
    <div class="col-sm-3 col-lg-2"><strong>{{ label }}</strong></div>
    <div class="col-sm-9 col-lg-10">{% if value %}{{ value }}{% else %}-{% endif %}</div>
</div>

members/templates/members/subscribe_form.html
{% extends "base_public.html" %}
{% load bootstrap4 %}

{% block title %}Become a Quadrivium member{% endblock %}

{% block content %}
    <h2>Become a member</h2>
    <p>
        Great that you're interested in becoming a member of Quadrivium, the student music association!
        Fill out the complete form to become a member or only leave your contact details if you're not yet sure and want
        more info.
    </p>
    <p>
        <small class="text-muted">
            Why we need these personal details is indicated in our
            <a href="https://esmgquadrivium.sharepoint.com/:b:/g/EdOOvjXmMr1Nndcz0TxlR7ABHp742itPXhYwOZFG43oJXA?e=iQZ7So"
               target="_blank">
                privacy document</a> (in Dutch).
        </small>
    </p>

    <form method="post" action="{% url 'members:subscribe' %}">
        {% csrf_token %}
        <div class="alert alert-info">
            If you're just interested, fill in your contact details and we will send an email with more information,
            around the beginning of the college year.
        </div>
        {% bootstrap_form_errors form type='non_fields' %}
        {% bootstrap_field form.first_name layout='horizontal' label_class='col-sm-3 col-form-label' field_class='col-sm-9' %}
        {% bootstrap_field form.last_name layout='horizontal' label_class='col-sm-3 col-form-label' field_class='col-sm-9' %}
        {% bootstrap_field form.email layout='horizontal' label_class='col-sm-3 col-form-label' field_class='col-sm-9' %}
        {% bootstrap_field form.phone_number layout='horizontal' label_class='col-sm-3 col-form-label' field_class='col-sm-9' %}
        {% bootstrap_field form.instruments layout='horizontal' label_class='col-sm-3 col-form-label' field_class='col-sm-9' %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">I'm interested</button>
        {% endbuttons %}
        <div class="alert alert-info">
            If you want to become a member fill in the other details here as well!
            We will reach out to you with all info and to complete the membership application.
            The yearly contribution fee for a membership is around 60 euros.
        </div>
        {% bootstrap_field form.initials layout='horizontal' label_class='col-sm-3 col-form-label' field_class='col-sm-9' %}
        {% bootstrap_field form.street layout='horizontal' label_class='col-sm-3 col-form-label' field_class='col-sm-9' %}
        {% bootstrap_field form.postal_code layout='horizontal' label_class='col-sm-3 col-form-label' field_class='col-sm-9' %}
        {% bootstrap_field form.city layout='horizontal' label_class='col-sm-3 col-form-label' field_class='col-sm-9' %}
        {% bootstrap_field form.country layout='horizontal' label_class='col-sm-3 col-form-label' field_class='col-sm-9' %}
        {% bootstrap_field form.gender layout='horizontal' label_class='col-sm-3 col-form-label' field_class='col-sm-9' %}
        {% bootstrap_field form.date_of_birth layout='horizontal' label_class='col-sm-3 col-form-label' field_class='col-sm-9' %}
        {% bootstrap_field form.preferred_language layout='horizontal' label_class='col-sm-3 col-form-label' field_class='col-sm-9' %}
        {% bootstrap_field form.is_student layout='horizontal' label_class='col-sm-3 col-form-label' field_class='col-sm-9' %}
        {% bootstrap_field form.field_of_study layout='horizontal' label_class='col-sm-3 col-form-label' field_class='col-sm-9' %}
        {% bootstrap_field form.iban layout='horizontal' label_class='col-sm-3 col-form-label' field_class='col-sm-9' %}
        {% bootstrap_field form.tue_card_number layout='horizontal' label_class='col-sm-3 col-form-label' field_class='col-sm-9' %}
        {% bootstrap_field form.remarks layout='horizontal' label_class='col-sm-3 col-form-label' field_class='col-sm-9' %}

        {% buttons %}
            <button type="submit" class="btn btn-primary">Become a member</button>
        {% endbuttons %}
    </form>

{% endblock %}

members/templates/members/subscribe_form_done.html
{% extends "base_public.html" %}

{% block title %}Become a Quadrivium member{% endblock %}

{% block content %}
    <h2>Thank you for your submission!</h2>
    <p>
        We'll get back to you. If you have any questions you can send them to
        <a href="mailto:secretaris@esmgquadrivium.nl">secretaris@esmgquadrivium.nl</a>.
    </p>

    <p>
        <a href="https://www.esmgquadrivium.nl/" class="btn btn-primary">Quadrivium website</a>
        <a href="{% url "members:subscribe" %}" class="btn btn-outline-primary">Another submission</a>
    </p>
{% endblock %}