activities/urls.py
from django.urls import path
from activities.views import ActivitiesView, ActivityView, MyActivityFormView, PastActivitiesView

app_name = "activities"

urlpatterns = [
    path('', ActivitiesView.as_view(), name="index"),
    path('past/', PastActivitiesView.as_view(), name="past"),
    path('activity/<int:id>/', ActivityView.as_view(), name="activity"),
    path('activity/<int:id>/edit/', MyActivityFormView.as_view(), name="myactivity"),
]

oidc/urls.py
from django.urls import path

from oidc import views

app_name = 'oidc'
urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('auth/', views.AuthView.as_view(), name='auth'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('loggedout/', views.LoggedOutView.as_view(), name='loggedout'),
]

tutti/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('oidc/', include('oidc.urls')),
    path('ht/', include('health_check.urls')),
    path('penno/', include('pennotools.urls')),
    path('duqduqgo/', include('duqduqgo.urls')),
    path('members/', include('members.urls')),
    path('activities/', include('activities.urls')),
    path('', include('pages.urls')),
]

activities/models.py
from django.db import models
from members.models import QGroup, Person
from django.utils import timezone


class Activity(models.Model):
    name = models.CharField(max_length=150)
    description = models.TextField(blank=True)
    hide_activity = models.BooleanField(default=False)
    hide_participants = models.BooleanField(default=False,
                                            help_text="Participants will be hidden for everyone except the organizers.")
    cost = models.CharField(max_length=150, help_text="Used for display only.", blank=True)
    location = models.CharField(max_length=150, blank=True)
    start_date = models.DateTimeField(help_text="Start time and date of the activity.")
    end_date = models.DateTimeField(null=True, blank=True, help_text="End time and date of the activity.")
    closing_date = models.DateTimeField(null=True,
                                        blank=True,
                                        help_text="Time and date enlisting closes.")
    groups = models.ManyToManyField(QGroup,
                                    blank=True,
                                    verbose_name='linked groups',
                                    help_text="You can restrict sign up to people from certain groups. "
                                              "If you don't specify a group, all (current) members can sign up.")
    participants = models.ManyToManyField(Person,
                                          blank=True,
                                          related_name='activity_set')
    owners = models.ManyToManyField(Person,
                                    blank=True,
                                    related_name='activity_organized_set',
                                    verbose_name='organizers',
                                    help_text="Organizers can modify the activity and get participant contact details.")

    class Meta:
        verbose_name_plural = 'activities'

    @property
    def is_closed(self):
        if self.closing_date:
            return timezone.now() > self.closing_date
        else:
            return timezone.now() > self.start_date

activities/forms.py
from django import forms

from activities.models import Activity


class ActivityForm(forms.ModelForm):
    """Allows the user to change an activity."""

    class Meta:
        model = Activity
        fields = ['name',
                  'description',
                  'cost',
                  'location',
                  'start_date',
                  'end_date',
                  'closing_date',
                  'hide_activity',
                  'hide_participants',
                  'groups',
                  ]

activities/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.utils import timezone
from django.views.generic import TemplateView, FormView, ListView

from activities.forms import ActivityForm
from activities.models import Activity
from members.models import Person, GroupMembership


def can_view_activity(person: Person, activity: Activity) -> bool:
    if person in activity.owners.all() or person.has_perm('activities.view_activity'):
        return True
    for membership in GroupMembership.objects.filter(user=person, end=None):
        for activity_group in activity.groups.all():
            if activity_group.id == membership.group.id and not activity.hide_activity:
                return True
    return False


def can_edit_activity(person: Person, activity: Activity) -> bool:
    # We can use the below permission to grant board members edit access for all activities
    return person in activity.owners.all() or person.has_perm('activities.change_activity')


class MyActivityFormView(LoginRequiredMixin, FormView):
    """Displays a form to edit an activity."""
    template_name = "activities/my_activity.html"
    form_class = ActivityForm
    success_url = reverse_lazy("activities:index")

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        # Check access
        activity = Activity.objects.get(id=self.kwargs['id'])
        if not can_edit_activity(self.request.user.person, activity):
            raise PermissionDenied
        kwargs["instance"] = Activity.objects.get(id=self.kwargs['id'])
        return kwargs

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class ActivitiesView(LoginRequiredMixin, ListView):
    """Displays a list of activities."""
    template_name = "activities/activities.html"

    def get_queryset(self):
        return Activity.objects.filter(start_date__gte=timezone.now()).order_by('start_date')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        person = self.request.user.person
        activities = []
        can_edit = []
        for activity in self.get_queryset():
            if can_view_activity(person, activity) and activity not in activities:
                activities.append(activity)
            if can_edit_activity(person, activity) and activity.id not in can_edit:
                can_edit.append(activity.id)

        context.update({
            "activities": activities,
            "can_edit": can_edit,
        })
        return context


class PastActivitiesView(ActivitiesView):
    template_name = 'activities/past_activities.html'

    def get_queryset(self):
        return Activity.objects.filter(start_date__lt=timezone.now()).order_by('-start_date')


class ActivityView(LoginRequiredMixin, TemplateView):
    """Displays an activity."""
    template_name = "activities/activity.html"

    def get_activity(self):
        """Returns the activity (if the user has view access)."""
        activity = Activity.objects.get(id=self.kwargs['id'])
        # Check permission
        if not can_view_activity(self.request.user.person, activity):
            raise PermissionDenied
        return activity

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        activity = self.get_activity()
        participants = activity.participants.all()
        persons = activity.participants.filter(username=self.request.user.username)
        context.update({
            "activity": activity,
            "participants": None if activity.hide_participants else participants,
            "is_subscribed": persons.exists(),
            "can_edit": can_edit_activity(self.request.user.person, activity),
        })
        return context

    def post(self, request, *args, **kwargs):
        # This might throw Person.DoesNotExist when accessed by a user without a related Person instance,
        #  but that only happens in development.
        person = request.user.person

        # Add or remove person from the activity
        activity = self.get_activity()
        if activity.is_closed:
            # Can't change enlistment when activity is closed
            raise PermissionDenied

        if 'signup' in request.POST:
            activity.participants.add(person)
        else:
            activity.participants.remove(person)

        return redirect('activities:activity', id=activity.id)

activities/templates/activities/activities.html
{% extends "base.html" %}

{% block title %}Activities | {{ block.super }}{% endblock %}

{% block content %}
    <h1>Activities</h1>
    {% for activity in activities %}
        {% include 'activities/activity_summary_card.html' %}
    {% endfor %}
    <a href="{% url 'activities:past' %}" class="btn btn-primary">Earlier activities</a>
{% endblock %}

activities/templates/activities/activity.html
{% extends "base.html" %}

{% block title %}{{ activity.name }} | {{ block.super }}{% endblock %}

{% block content %}
    <h1>Activities</h1>
    <div class="card">
        <div class="card-header">
            {{ activity.start_date.date }}
        </div>
        <div class="card-body">
            <h5 class="card-title">{{ activity.name }}</h5>
            <div class="row">
                <div class="col-sm-8"><p>{{ activity.description }}</p></div>
                <div class="col-sm-4">
                    <div><strong>Start</strong> {{ activity.start_date.time }}</div>
                    {% if activity.end_date %}
                        {# Display only time if the date is equal to start, else display full datetime #}
                        <div>
                            <strong>End</strong>
                            {% if activity.end_date.date == activity.start_date.date %}
                                {{ activity.end_date.time }}
                            {% else %}
                                {{ activity.end_date }}
                            {% endif %}
                        </div>
                    {% endif %}
                    <div><strong>Location</strong> {{ activity.location }}</div>
                    {% if activity.closing_date %}
                        <div><strong>Enlist before</strong> {{ activity.closing_date }}</div>
                    {% endif %}
                    <div><strong>Cost</strong> {{ activity.cost }}</div>
                </div>
            </div>
            {% if not activity.is_closed %}
                <form method="post" style="display: inline;">
                    {% csrf_token %}
                    {% if is_subscribed %}
                        <button type="submit" name="signout" class="btn btn-light">Sign out</button>
                    {% else %}
                        <button type="submit" name="signup" class="btn btn-primary">Sign up!</button>
                    {% endif %}
                </form>
            {% endif %}
            {% if can_edit %}
                <a href="{% url 'activities:myactivity' id=activity.id %}"
                   class="btn btn-danger float-lg-right">Edit
                </a>
            {% endif %}
        </div>
    </div>
    <p></p>
    <ul class="list-group">
        {% for participant in participants %}
            <li class="list-group-item">{{ participant }}</li>
        {% endfor %}
    </ul>
{% endblock %}

activities/templates/activities/activity_summary_card.html
<div class="card {{ activity.hide_activity|yesno:'text-white bg-secondary,' }} mb-3">
    <div class="card-header">{{ activity.start_date.date }}</div>
    <div class="card-body">
        <h5 class="card-title">{{ activity.name }}</h5>
        <p class="card-text">{{ activity.description|truncatechars:300 }}</p>
        <a href="{% url 'activities:activity' id=activity.id %}" class="btn btn-primary">More info</a>
        {% if activity.id in can_edit %}
            <a href="{% url 'activities:myactivity' id=activity.id %}" class="btn btn-danger float-lg-right">Edit</a>
        {% endif %}
    </div>
</div>

activities/templates/activities/mini_activities.html
<div class="list-group">
  {% for activity in activities %}
  <a href="{% url 'activities:activity' id=activity.id %}"
     class="list-group-item list-group-item-action text-truncate">{{activity.name}}
  </a>
  {% endfor %}}
</div>

activities/templates/activities/my_activity.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block title %}Edit activity {{activity.id}} | {{ block.super }}{% endblock %}

{% block content %}
<h1>Edit activity</h1>
<form method="post">
  {% csrf_token %}
  {% bootstrap_form form layout="horizontal" %}
  {% buttons %}
  <button type="submit" class="btn btn-primary">Save</button>
  {% endbuttons %}
</form>

<table class="table table-striped">
  <thead>
  <tr>
    <th scope="col">Name</th>
    <th scope="col">E-mail</th>
    <th scope="col">Phone number</th>
    <th scope="col">ID</th>
  </tr>
  </thead>
  <tbody>
  {% for participant in form.instance.participants.all %}
  <tr>
    <th scope="row">{{participant}}</th>
    <td>{{participant.email}}</td>
    <td>{{participant.phone_number}}</td>
    <td>{{participant.person_id}}</td>
  </tr>
  {% endfor %}
  </tbody>
</table>
{% endblock %}

activities/templates/activities/past_activities.html
{% extends "base.html" %}

{% block title %}Activities | {{ block.super }}{% endblock %}

{% block content %}
    <h1>Finished activities</h1>
    {% for activity in activities %}
        {% include 'activities/activity_summary_card.html' %}
    {% endfor %}
{% endblock %}